config/routes.rb
Treebook::Application.routes.draw do
  get "profiles/show"
  devise_for :users

  resources :statuses

  root "statuses#index"

  get "profiles/:id", to: "profiles#show", as: "profiles"
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user

  validates :content, presence: true,
                      length: { minimum: 2 }

  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                             with: /\A[a-zA-Z0-9_-]+\z/,
                             on: :create,
                             message: "must be formatted correctly."
                           }

  has_many :statuses

  def full_name
    "#{first_name} #{last_name}"
  end

  def gravatar_url
    hashed_email = Digest::MD5.hexdigest email.strip.downcase
    "http://gravatar.com/avatar/#{hashed_email}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    custom_fields = [:first_name, :last_name, :profile_name]
    devise_parameter_sanitizer.for(:sign_up) << custom_fields
    devise_parameter_sanitizer.for(:account_update) << custom_fields
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    if @user
      @statuses = @user.statuses
      render :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :set_status, only: [:show, :edit, :update, :destroy]


  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all.reverse_order
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)
    @status.user = current_user

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/_flashes.html.erb
<% foundation_flash_map = { notice: 'success',
                            alert: 'standard',
                            error: 'alert',
                            secondary: 'secondary'
} %>

<% flash.each do |type, message| %>
  <div data-alert class="alert-box #{ foundation_flash_map[type] } radius">
    <%= message %>
    <%= link_to "x", "#", class: "close" %>
  </div>
<% end %>

app/views/layouts/_flashy.html.erb
<% foundation_alerts = { notice: 'success',
                            alert: 'standard',
                            error: 'alert',
                            secondary: 'secondary'
} %>

<% if flash %>
  <% flash.each do |type, message| %>
    <div data-alert class="alert-box <%= foundation_alerts[type] %> radius">
      <%= message %>
      <%= link_to "x", "#", class: "close" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Treebook" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar hide-for-small">
      <!-- Title Area -->
      <ul class="title-area">
        <!-- Title Area -->
        <li class="name">
          <h1><a href="/">Treebook</a></h1>
        </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon">
          <a href="#"><span>Menu</span></a>
        </li>
      </ul>
      <section class="top-bar-section">
        <!-- Left Nav Section -->
        <ul class="left">
          <li class="divider"></li>
          <li class=""><%= link_to "All statuses", statuses_path %></li>
          <% if user_signed_in? %>
            <li class="divider"></li>
            <li class="">
              <%= link_to "My statuses", profiles_path(current_user) %>
            </li>
          <% end %>
        </ul>
        <!-- Right Nav Section -->
        <ul class="right">
          <% if user_signed_in? %>
            <li class="">
              <%= link_to current_user.full_name, edit_user_registration_path %>
            </li>
            <li class="divider"></li>
            <li class="">
              <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="">
              <%= link_to "Log In", new_user_session_path %>
            </li>
            <li class="divider"></li>
            <li class="">
              <%= link_to "Register", new_user_registration_path %>
            </li>
          <% end %>

        </ul>
      </section>
    </nav>

    <section class="main">
      <div class="row">
        <div class="large-12 columns">
          <%= render 'layouts/flashy' %>
          <%= yield %>
        </div>
      </div>
    </section>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/profiles/show.html.erb
<div class="well">
  <h2><%= @user.full_name %></h2>

  <% if @statuses %>
    <% @statuses.each do |status| %>
      <div class="row">
        <div class="large-6 columns">
          <p>
            <h4><%= link_to status.content, status_path(status) %></h4>
            -- <em><%= time_ago_in_words(status.created_at) %> ago</em>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>All statuses</h1>
</div>

<%= link_to 'Post a New Status', new_status_path, class: "button radius" %>

<% @statuses.each do |status| %>
  <div class="status">
    <div class="row">
      <div class="small-2 large-2 columns">
        <%= image_tag status.user.gravatar_url %>
      </div>
      <div class="small-10 large-10 columns">
        <strong><%= status.user.profile_name %></strong>
        <p><%= status.content %></p>
        <div class="meta">
          <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
          <span class="admin">
            | <%= link_to "", edit_status_path(status), class: "general fi-pencil",
                  title: "edit" %>
            | <%= link_to "", status, method: :delete, class: "general fi-x",
                  title: "delete",
                  data: { confirm: "Are you sure you want to delete this status?"} %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @status.user.profile_name %><br />
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>